Capstone 1
samreenmj/capstone-project pull request #2
Opened 2023-03-24 08:11 UTC by samreenmj

#### built  these 2 pages:

The home page.
The about page.
Each of these pages have versions for 2 different screen sizes:

Mobile: up to 768px wide.
Desktop: 768px or wider.

Links
The home page have a link in the menu to the about page.
The logo in the header links to the home page.
Mobile menu
When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.

The mobile menu have a close (X) button that closes the menu.

2023-03-24 16:41 UTC, mukhammadrizooff requested changes
Hi @samreenmj, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- No linter errors ✔️ 
- Correct GitHub Flow ✔️ 
- Good implementations ✔️ 

## Required Changes ♻️
- [ ] [REQUIRED] Good job so far! You should record a `video presenting` the features of the project but I couldn't find it, please implement it 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/227587589-b0ec42a8-8ce0-40a1-a667-96f59d7ce5a1.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 16:41 UTC, mukhammadrizooff commented on about.html
> +            <a class="last"><img class="footer-logo" src="./images/creative common korea footer logo.png" alt="img"></a>
- [ ] [REQUIRED] Good job so far! Please fix the positioning of your footer elements 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/227585164-7f0bb2a7-2b08-439f-ac42-58673763f099.png)

2023-03-24 16:41 UTC, mukhammadrizooff commented on about.html
> +            <h2 class="title">Partners</h2>
- [ ] [REQUIRED] Good job so far! Please give the correct style to `Highlight` on the picture below:

![image](https://user-images.githubusercontent.com/63915024/227585984-b6be51d4-5514-4d63-a419-4126819071eb.png)

2023-03-24 16:41 UTC, mukhammadrizooff commented on about.html
> +      <p class="small">"Hello! Sharing World"</p>
- [ ] [REQUIRED] It would be more semantic if you change `p` tag to `hx` tag 👍🏼

2023-03-24 16:41 UTC, mukhammadrizooff commented on about.html
> +       <header>
- [ ] [REQUIRED] Good job so far! Please don't put your site's `header`/`menu`/`footer` (repeated content) in your `<main>` tag because it is not semantically nice 👍🏼

2023-03-24 16:41 UTC, mukhammadrizooff commented on about.css
- [ ] [REQUIRED] Good job so far! Please `style` your `about` page correctly, just like [Behance](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), because you need to rework your `about` page elements on `placement`, `font` size, and `background` picture 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/227582904-20226562-9ecd-4d5d-9e33-6e447535be80.png)

![image](https://user-images.githubusercontent.com/63915024/227584324-dcb4342f-987e-4627-bec2-f86d15052d41.png)

2023-03-24 16:41 UTC, mukhammadrizooff commented on js/script.js
> +    image: './images/ermi_480.jpg',
- [ ] [REQUIRED] Good job so far! Please add a chess background figure to each speaker's picture and give correct style to mobile version 🙏🏼 

### Desktop
![image](https://user-images.githubusercontent.com/63915024/227580038-bd13d1c4-4fdc-43f9-9a59-a840b349889f.png)

### Mobile 
![image](https://user-images.githubusercontent.com/63915024/227580106-c1554bcf-0cbd-4ea1-a7d0-ec0f58aafcc2.png)

2023-03-24 16:41 UTC, mukhammadrizooff commented on index.html
> + <header class="header">
- [ ] [REQUIRED] Good job so far! Please don't put your site's `header`/`menu`/`footer` (repeated content) in your `<main>` tag because it is not semantically nice 👍🏼

2023-03-24 16:41 UTC, mukhammadrizooff commented on index.html
> +<section class="home-page">
- [ ] [REQUIRED] The `navigation` part and `content` parts of your `Home` page are folded and the design of the `content texts` is also different from the [Behance design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015). Please style them like the design on [Behance](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) and choose the right background picture and fonts 🙏🏼 

### Your Design
- Desktop
![image](https://user-images.githubusercontent.com/63915024/227574124-342f5219-6f33-4782-899d-1c89028242dd.png)

- Mobile
![image](https://user-images.githubusercontent.com/63915024/227574493-b8a06e52-cd32-4585-89e8-10daf8a5cab7.png)


### [Behance Design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)

![image](https://user-images.githubusercontent.com/63915024/227574812-868bf6ef-9824-4683-92d9-e0aeb30e9a5f.png)

2023-03-24 16:41 UTC, mukhammadrizooff commented on index.html
> +    <h2 class="about-section">Main Program</h2>
- [ ] [REQUIRED] Good job so far! Please set the correct color to the main text and card icons also give the correct `font-weight` like a [Behance design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/227576771-9bc15f03-1156-4e5f-aad3-1bc8d51d479d.png)

2023-03-24 16:41 UTC, mukhammadrizooff commented on README.md
> +This project is under [MIT](./LICENSE) licensed.
- [ ] [REQUIRED] Kindly your `MIT` license is not working, please fix it 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/227587120-3b056539-1930-4655-be5d-6101f2538713.png)

2023-03-24 16:41 UTC, mukhammadrizooff commented on README.md
> +
- [ ] [REQUIRED] You should make use of `GitHub Pages` to deploy the web pages. The project shoud be deployed properly, and all pages, links, and images work as expected. A link to the deployed project is present in the `README`. Please implement my suggestions 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/227586859-4625895f-78c1-4f25-adcd-2af9e68dde6a.png)

2023-03-25 19:01 UTC, arslanbisharat commented
Hi @samreenmj,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 19:19 UTC, merged